"""remove_id_index

Revision ID: a74e3193ec03
Revises: 9dde969a1700
Create Date: 2026-08-12 23:36:14.223399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74e3193ec03'
down_revision: Union[str, None] = '9dde969a1700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_defects_id', table_name='defects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_defects_id', 'defects', ['id'], unique=False)
    # ### end Alembic commands ###
